all: build

clean:
	make -C ./Src clean
	make -C ./T4/Src clean
	make -C ./JPEG/Src clean
	make -C ./WT/Src clean

build:
	make -C ./Src
	make -C ./T4/Src
	make -C ./JPEG/Src
	make -C ./WT/Src

depend:
	make -C ./Src depend
	make -C ./T4/Src depend
	make -C ./JPEG/Src depend
	make -C ./WT/Src depend
